// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoWdI_E0-0ecr7GlN-5MWzHfgbvS2UNIg',
    appId: '1:604044337347:web:60deb304d0761eb77d0276',
    messagingSenderId: '604044337347',
    projectId: 'sam-mood-app-2bdbd',
    authDomain: 'sam-mood-app-2bdbd.firebaseapp.com',
    storageBucket: 'sam-mood-app-2bdbd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAidXCJ4wmnBb2vRsgoGZCLs2QquNVx5sg',
    appId: '1:604044337347:android:a5acc60f950623587d0276',
    messagingSenderId: '604044337347',
    projectId: 'sam-mood-app-2bdbd',
    storageBucket: 'sam-mood-app-2bdbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV-VWXT4RFE4aHgCvESe9B5BODprkYfKg',
    appId: '1:604044337347:ios:864c2b8a94731ec77d0276',
    messagingSenderId: '604044337347',
    projectId: 'sam-mood-app-2bdbd',
    storageBucket: 'sam-mood-app-2bdbd.appspot.com',
    iosBundleId: 'com.example.samMoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV-VWXT4RFE4aHgCvESe9B5BODprkYfKg',
    appId: '1:604044337347:ios:9285531fea32bd757d0276',
    messagingSenderId: '604044337347',
    projectId: 'sam-mood-app-2bdbd',
    storageBucket: 'sam-mood-app-2bdbd.appspot.com',
    iosBundleId: 'com.example.samMoodApp.RunnerTests',
  );
}
